### ISSUE TITLE
Checkpoint file for chemCPA

### ISSUE THREAD

**Issue by shalini565** [mims-harvard/Madrigal#3]
In the config file for transcriptomics, model checkpoint is being provided but I wasn't able to see the file anywhere. The config file (chemcpa_finetune_configs.yaml) where the checkpoint is referring to:
```
fixed:
  # model.load_pretrained: False
  model.pretrained_model_ckpt: 2023-09-03_09:44_tx_adapting_full_test_not_use_drugs.pt
  model.additional_params.decoder_activation: linear
  model.additional_params.doser_type: amortized 

```
Also it's being used in models.py for the pretrained model:
```
  else:
            print('Using pretrained TX encoder')
            (
                state_dict,
                _,
                cov_embeddings_state_dicts,
                model_config,
                history,
            ) = torch.load(BASE_DIR+"model_output/pretrain/adapting/tx/checkpoints/"+pretrained_model_ckpt, map_location=torch.device('cpu'))  # would be `2023-09-03_09:44_tx_adapting_full_test_not_use_drugs.pt` if using the full model
            assert model_config['use_drugs'] == use_drugs, 
```

It would be great if you can share the checkpoint file.
